# Generated by Django 4.2.26 on 2025-11-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability_type',
            field=models.CharField(choices=[('レンタルのみ', 'レンタルのみ'), ('販売のみ', '販売のみ'), ('レンタル・販売両方', 'レンタル・販売両方')], default='レンタル・販売両方', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='available_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='max_rental_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='product',
            name='min_rental_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='owner_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
