# Generated by Django 4.2.26 on 2025-11-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_rentalapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rental',
            name='product_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rental',
            name='received_date_by_renter',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='rental_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='renter_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='shipped_date_return',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='shipped_date_to_renter',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='total_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rental',
            name='tracking_number_return',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rental',
            name='tracking_number_to_renter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('申請中', '申請中'), ('承認済み', '承認済み'), ('発送済み', '発送済み'), ('レンタル中', 'レンタル中'), ('返却発送済み', '返却発送済み'), ('返却済み', '返却済み'), ('完了', '完了'), ('キャンセル', 'キャンセル')], default='申請中', max_length=20),
        ),
    ]
