# Generated by Django 4.2.26 on 2025-11-27 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0004_rental_completed_date_rental_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ('-created_at',)},
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='purchase',
                    name='price',
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='purchase',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='purchase',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='purchase',
            name='product_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='purchase',
            name='return_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='return_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='purchase',
            name='return_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='return_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='return_shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='return_status',
            field=models.CharField(choices=[('NONE', 'なし'), ('REQUESTED', '申請中'), ('APPROVED', '承諾済'), ('SHIPPED', '返送済み'), ('RECEIVED', '受領済み'), ('REJECTED', '却下')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='return_tracking_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='purchase',
            name='seller_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='purchase',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='purchase',
            name='shipping_postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('申請中', '申請中'), ('承認済み', '承認済み'), ('発送済み', '発送済み'), ('完了', '完了'), ('キャンセル', 'キャンセル')], default='申請中', max_length=10),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['status'], name='marketplace_status_1bbb01_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['buyer_email'], name='marketplace_buyer_e_099d17_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['seller_email'], name='marketplace_seller__348890_idx'),
        ),
        migrations.AddField(
            model_name='productfavorite',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='marketplace.product'),
        ),
        migrations.AddField(
            model_name='productfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='productfavorite',
            index=models.Index(fields=['user', 'product'], name='marketplace_user_id_2d7f2b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productfavorite',
            unique_together={('user', 'product')},
        ),
    ]
