<<<<<<< HEAD
# Generated by Django 4.2.26 on 2025-11-19 01:00
=======
# Generated by Django 4.2.26 on 2025-11-25 05:35
>>>>>>> cb624c1 (変更要約)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_rental_completed_date_rental_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='price',
        ),
        migrations.AddField(
            model_name='purchase',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='purchase',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='purchase',
            name='product_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='purchase',
<<<<<<< HEAD
=======
            name='return_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='return_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='purchase',
            name='return_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='return_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='return_shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='return_status',
            field=models.CharField(choices=[('NONE', 'なし'), ('REQUESTED', '申請中'), ('APPROVED', '承諾済'), ('SHIPPED', '返送済み'), ('RECEIVED', '受領済み'), ('REJECTED', '却下')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='return_tracking_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='purchase',
>>>>>>> cb624c1 (変更要約)
            name='seller_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='purchase',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('申請中', '申請中'), ('発送済み', '発送済み'), ('完了', '完了'), ('キャンセル', 'キャンセル')], default='申請中', max_length=10),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['status'], name='marketplace_status_1bbb01_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['buyer_email'], name='marketplace_buyer_e_099d17_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['seller_email'], name='marketplace_seller__348890_idx'),
        ),
    ]
