# Generated by Django 4.2.26 on 2025-11-26 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_productfavorite_alter_purchase_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productfavorite',
            name='marketplace_product_396c08_idx',
        ),
    ]
