# Generated by Django 4.2.26 on 2025-11-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_purchase_options_remove_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='shipping_postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('申請中', '申請中'), ('承認済み', '承認済み'), ('発送済み', '発送済み'), ('完了', '完了'), ('キャンセル', 'キャンセル')], default='申請中', max_length=10),
        ),
    ]
