# Generated by Django 4.2.26 on 2025-11-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_productfavorite_alter_purchase_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalapplication',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='status',
            field=models.CharField(choices=[('pending', '申請中'), ('approved', '承認済み'), ('shipped', '発送済み'), ('received', '受取完了'), ('return_shipped', '返却発送済み'), ('completed', '完了'), ('rejected', '却下'), ('cancelled', 'キャンセル')], default='pending', max_length=20),
        ),
    ]
