# Generated by Django 4.2.26 on 2025-11-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_purchase_options_remove_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='return_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='purchase',
            name='return_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='return_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='return_status',
            field=models.CharField(choices=[('NONE', 'なし'), ('REQUESTED', '申請中'), ('SHIPPED_BACK', '返送中'), ('RECEIVED', '受領済み'), ('REJECTED', '却下')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='return_tracking_number',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
