# Generated by Django 4.2.26 on 2025-11-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_purchase_return_reason_purchase_return_received_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='return_status',
            field=models.CharField(choices=[('NONE', '返品なし'), ('REQUESTED', '申請中'), ('ALLOWED', '返送許可'), ('SHIPPED_BACK', '返送済み'), ('RECEIVED_BACK', '受領済み'), ('REJECTED', '却下')], default='NONE', max_length=20),
        ),
    ]
