# Generated by Django 4.2.26 on 2025-11-27 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_remove_productfavorite_marketplace_product_396c08_idx'),
        ('marketplace', '0006_rentalapplication_tracking_number_and_more'),
    ]

    operations = [
    ]
