# Generated by Django 4.2.26 on 2025-11-27 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0006_ensure_productfavorite"),
        ("marketplace", "0007_merge_20251127_1134"),
    ]

    operations = []
