# Generated by Django 4.2.26 on 2025-11-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_purchase_return_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='return_status',
            field=models.CharField(choices=[('NONE', 'なし'), ('REQUESTED', '申請中'), ('SHIPPED_BACK', '返送中'), ('RECEIVED', '受領済み'), ('REJECTED', '却下')], default='NONE', max_length=20),
        ),
    ]
