# Generated by Django 4.2.26 on 2026-01-08 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_merge_20251127_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('rental', 'レンタル'), ('purchase', '購入')], max_length=10)),
                ('direction', models.CharField(choices=[('outbound', '発送（出品者→購入者 / 貸主→借主）'), ('inbound', '返送（購入者→出品者 / 借主→貸主）')], max_length=10)),
                ('from_name', models.CharField(blank=True, max_length=120)),
                ('from_phone', models.CharField(blank=True, max_length=40)),
                ('from_postal', models.CharField(blank=True, max_length=20)),
                ('from_address', models.CharField(blank=True, max_length=255)),
                ('to_name', models.CharField(blank=True, max_length=120)),
                ('to_phone', models.CharField(blank=True, max_length=40)),
                ('to_postal', models.CharField(blank=True, max_length=20)),
                ('to_address', models.CharField(blank=True, max_length=255)),
                ('tracking_no', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('created', '作成'), ('in_transit', '輸送中'), ('delivered', '配達完了'), ('canceled', 'キャンセル')], default='created', max_length=12)),
                ('is_platform_intermediated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='marketplace.product')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='marketplace.purchase')),
                ('rental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='marketplace.rental')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status'], name='marketplace_status_92feae_idx'), models.Index(fields=['tracking_no'], name='marketplace_trackin_72a933_idx'), models.Index(fields=['direction'], name='marketplace_directi_c51e77_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(fields=('rental', 'direction'), name='uniq_shipment_rental_dir'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(fields=('purchase', 'direction'), name='uniq_shipment_purchase_dir'),
        ),
    ]
