# Generated by Django 4.2.26 on 2025-11-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_alter_purchase_return_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='return_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='return_shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='return_status',
            field=models.CharField(choices=[('NONE', 'なし'), ('REQUESTED', '申請中'), ('APPROVED', '承諾済'), ('SHIPPED', '返送済み'), ('RECEIVED', '受領済み'), ('REJECTED', '却下')], default='NONE', max_length=20),
        ),
    ]
