# Generated by Django 4.2.26 on 2026-01-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_shipment_shipment_uniq_shipment_rental_dir_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shipment',
            name='uniq_shipment_rental_dir',
        ),
        migrations.RemoveConstraint(
            model_name='shipment',
            name='uniq_shipment_purchase_dir',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='direction',
            field=models.CharField(choices=[('outbound', '往路'), ('return', '返送'), ('inbound', '受領側（内部用）')], max_length=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='from_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='from_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='from_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='from_postal',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='to_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='to_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='to_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='to_postal',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['kind'], name='marketplace_kind_402619_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['rental'], name='marketplace_rental__565556_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['purchase'], name='marketplace_purchas_c0a357_idx'),
        ),
    ]
