# Generated by Django 4.2.26 on 2026-01-08 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_remove_shipment_uniq_shipment_rental_dir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='marketplace.rentalapplication'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['application'], name='marketplace_applica_5c8f9e_idx'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(condition=models.Q(('rental__isnull', False)), fields=('rental', 'direction'), name='uniq_shipment_rental_direction'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(condition=models.Q(('purchase__isnull', False)), fields=('purchase', 'direction'), name='uniq_shipment_purchase_direction'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(condition=models.Q(('application__isnull', False)), fields=('application', 'direction'), name='uniq_shipment_application_direction'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('kind', 'rental'), models.Q(('rental__isnull', False), ('application__isnull', False), _connector='OR'), ('purchase__isnull', True)), models.Q(('kind', 'purchase'), ('purchase__isnull', False), ('rental__isnull', True), ('application__isnull', True)), _connector='OR'), name='chk_shipment_kind_fk_consistency'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.CheckConstraint(check=models.Q(('rental__isnull', False), ('application__isnull', False), _negated=True), name='chk_shipment_rental_xor_application'),
        ),
    ]
