# Generated by Django 4.2.26 on 2026-01-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0011_shipment_application_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalapplication",
            name="return_tracking_number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
