# Generated by Codex on 2026-01-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0012_rentalapplication_return_tracking_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="from_rental",
            field=models.BooleanField(default=False),
        ),
    ]
