# Generated by Codex on 2026-01-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0014_rentalapplication_hidden_by_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalapplication",
            name="hidden_by_renter",
            field=models.BooleanField(default=False),
        ),
    ]
