# Generated by Codex on 2026-01-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0015_rentalapplication_hidden_by_renter"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="hidden_by_buyer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="purchase",
            name="hidden_by_seller",
            field=models.BooleanField(default=False),
        ),
    ]
