# Generated by Codex on 2026-01-14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        ("marketplace", "0012_rentalapplication_return_tracking_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_rooms",
                to="marketplace.rentalapplication",
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="purchase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_rooms",
                to="marketplace.purchase",
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="rental",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_rooms",
                to="marketplace.rental",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatroom",
            constraint=models.UniqueConstraint(
                condition=models.Q(("rental__isnull", False)),
                fields=("rental",),
                name="uniq_chatroom_rental",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatroom",
            constraint=models.UniqueConstraint(
                condition=models.Q(("purchase__isnull", False)),
                fields=("purchase",),
                name="uniq_chatroom_purchase",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatroom",
            constraint=models.UniqueConstraint(
                condition=models.Q(("application__isnull", False)),
                fields=("application",),
                name="uniq_chatroom_application",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatroom",
            constraint=models.CheckConstraint(
                check=(
                    models.Q(("rental__isnull", True), ("purchase__isnull", True), ("application__isnull", True))
                    | models.Q(("rental__isnull", False), ("purchase__isnull", True), ("application__isnull", True))
                    | models.Q(("rental__isnull", True), ("purchase__isnull", False), ("application__isnull", True))
                    | models.Q(("rental__isnull", True), ("purchase__isnull", True), ("application__isnull", False))
                ),
                name="chk_chatroom_single_transaction",
            ),
        ),
    ]
