# Generated by Django 4.2.26 on 2025-11-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='簡易フラグ。role=admin と同等扱い。'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', '一般'), ('admin', '管理者')], default='user', max_length=20),
        ),
    ]
