@startuml
hide circle
skinparam classAttributeIconSize 0
left to right direction
skinparam linetype ortho
skinparam nodesep 35
skinparam ranksep 45

class "ユーザー" as User

class "商品" as Product {
  商品名
  状態
}

class "レンタル" as Rental
class "購入" as Purchase
class "レンタル申請" as RentalApplication

class "チャットルーム" as ChatRoom {
  作成日時
}

class "チャットメッセージ" as ChatMessage {
  本文
  既読
  作成日時
}

ChatRoom "0..*" --> "1" Product
ChatRoom "0..*" --> "1" User : ユーザー1
ChatRoom "0..*" --> "1" User : ユーザー2
ChatRoom "0..*" --> "0..1" Rental
ChatRoom "0..*" --> "0..1" Purchase
ChatRoom "0..*" --> "0..1" RentalApplication

ChatMessage "0..*" --> "1" ChatRoom
ChatMessage "0..*" --> "1" User : 送信者

@enduml
